export const GAME_EVENTS = {
  PLAYER_JOINED_NOTIFY: 'PLAYER_JOINED_NOTIFY',
  GET_GAME_STATE: 'GET_GAME_STATE',
  GET_GAME_STATE_NOTIFY: 'GET_GAME_STATE_NOTIFY',
  START_GAME: 'START_GAME',
  START_GAME_NOTIFY: 'START_GAME_NOTIFY',
  START_GAME_ERROR: 'START_GAME_ERROR',
  ROLL_DICE: 'ROLL_DICE',
  ROLL_DICE_NOTIFY: 'ROLL_DICE_NOTIFY',
  ROLL_DICE_ERROR: 'ROLL_DICE_ERROR',
  MOVE_PAWN: 'MOVE_PAWN',
  MOVE_PAWN_NOTIFY: 'MOVE_PAWN_NOTIFY',
  PAWN_CAPTURE_NOTIFY: 'PAWN_CAPTURE_NOTIFY'
}
