export const BOARD_CONTAINER_SIZE = 750
export const NO_OF_SQUARES_BETWEEN_HOMES = 3
export const NO_OF_SQUARES_ALONG_HOMES = 6
export const SMALL_BOX_SIZE = 50
export const BOARD_SIZE =
  NO_OF_SQUARES_ALONG_HOMES * SMALL_BOX_SIZE * 2 +
  NO_OF_SQUARES_BETWEEN_HOMES * SMALL_BOX_SIZE
export const WIDTH_OF_SQUARES_ALONG_HOME =
  SMALL_BOX_SIZE * NO_OF_SQUARES_BETWEEN_HOMES
export const PLAYER_HOME_SIZE =
  BOARD_SIZE - BOARD_SIZE / 2 - WIDTH_OF_SQUARES_ALONG_HOME / 2
export const MARGIN_FOR_HOME_INNER_SQUARE = PLAYER_HOME_SIZE / 3
export const PLAYER_HOME_INNER_SQUARE_SIZE =
  PLAYER_HOME_SIZE - MARGIN_FOR_HOME_INNER_SQUARE

export const COLORS = {
  LIGHT_GRAY: '#f5f5f5',
  GREEN: '#2ec1ac',
  RED: '#ea5455',
  YELLOW: '#fdb827',
  BLUE: '#035aa6',
  ORANGE: 'orange',
  WHITE: 'white',
  BLACK: 'black'
}

export const SEAT_COLORS = {
  1: COLORS.RED,
  2: COLORS.YELLOW,
  3: COLORS.BLUE,
  4: COLORS.GREEN
}

export const GAME_EVENTS = {
  PLAYER_JOINED_NOTIFY: 'PLAYER_JOINED_NOTIFY',
  GET_GAME_STATE: 'GET_GAME_STATE',
  GET_GAME_STATE_NOTIFY: 'GET_GAME_STATE_NOTIFY',
  START_GAME: 'START_GAME',
  START_GAME_NOTIFY: 'START_GAME_NOTIFY',
  START_GAME_ERROR: 'START_GAME_ERROR',
  ROLL_DICE: 'ROLL_DICE',
  ROLL_DICE_NOTIFY: 'ROLL_DICE_NOTIFY',
  ROLL_DICE_ERROR: 'ROLL_DICE_ERROR',
  MOVE_PAWN: 'MOVE_PAWN',
  MOVE_PAWN_NOTIFY: 'MOVE_PAWN_NOTIFY'
}
